Fix error when reading material indices
In Blender 3.4, material indices became integers instead of shorts,
resulting in an error when reading them into a short buffer:
  TypeError: couldn't access the py sequence
This patch fixes that by using an integer buffer instead.

Fixes #1891.